ARCH_CFLAGS += -march=armv8-a
ARCH_AFLAGS +=
ARCH_LDFLAGS +=

core-y += arch/aarch64/kernel/
core-y += arch/aarch64/mm/
core-y += arch/aarch64/ld_script/
core-y += arch/aarch64/dts/
core-y += arch/aarch64/mmu_v2/
