name: Makefile CI

on:
  push:
    branches: [ "eeos" ]
  pull_request:
    branches: [ "eeos" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure
      run: echo "start build"

