ARCH_CFLAGS += -march=rv64im -mabi=lp64 -mcmodel=medany
ARCH_AFLAGS +=
ARCH_LDFLAGS +=

core-y += arch/riscv64/boot/
core-y += arch/riscv64/ld_script/
core-y += arch/riscv64/mm/
core-y += arch/riscv64/kernel/
core-y += arch/riscv64/dts/
