ARCH_CFLAGS += -march=rv64im -mabi=lp64 -fno-stack-protector -mcmodel=medany
ARCH_AFLAGS += -march=rv64im -mabi=lp64 -fno-stack-protector -mcmodel=medany
ARCH_LDFLAGS +=

head-y += arch/riscv64/boot/startup.o
core-y += arch/riscv64/boot/
